import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <Header/>
        <DropdownMenu>
          <DropdownMenuTrigger>
            <Button>Calculadoras</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>Calculadoras</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Calculadora Padrão</DropdownMenuItem>
            <DropdownMenuItem>Calculadora de Matrizes</DropdownMenuItem>
            <DropdownMenuItem>Calculadora de Equações</DropdownMenuItem>
            <DropdownMenuItem>Calculadora de Ano Bissexto</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
